# Generated by Django 4.2.3 on 2024-08-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_category_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('ELE', 'Electronics'), ('FAS', 'Fashion'), ('HOM', 'Home & Garden'), ('SPO', 'Sports & Outdoors'), ('AUT', 'Automotive'), ('COL', 'Collectibles & Art'), ('TOY', 'Toys & Hobbies'), ('BOK', 'Books & Media'), ('REA', 'Real Estate'), ('OTH', 'Other')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auctions/media/listing_images'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
