# Generated by Django 5.1 on 2024-08-17 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='Listing',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='date',
        ),
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_listing', to='auctions.bid'),
        ),
    ]
