# Generated by Django 5.1 on 2024-08-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_bid_listing_remove_bid_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='active',
            new_name='state',
        ),
    ]
