# Generated by Django 5.1 on 2024-08-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_rename_active_listing_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Listing',
            new_name='listing',
        ),
    ]
